dados = input().split(' ')
A, B, C = dados
A = float(A)
B = float(B)
C = float(C)
T = (A*C/2)
R = (3.14159*C**2)
TZ = ((A+B)*C/2)
Q = (B*B)
RT = (A*B)
print ("TRIANGULO: %.3f"%T)
print ("CIRCULO: %.3f"%R)
print ("TRAPEZIO: %.3f"%TZ)
print ("QUADRADO: %.3f"%Q)
print ("RETANGULO: %.3f"%RT)